### ISSUE TITLE
how to use api?

### ISSUE THREAD

**Issue by kitoraosu** [norn/bustime#1]
https://api.busti.me

**Comment by norn** [comment]
https://api.busti.me/ is used for internal communication with mobile clients. It is not public available. We don't provide public API for real-time vehicle position (license limitation), you have to ask data owners.

**Comment by nikolaychernov** [comment]
То есть подключиться, как описано здесь https://ru.busti.me/services/, можно только в том плане, что перевозчик будет отправлять свои данные в bustime? А получить эти собранные данные никак нельзя, можно только поднять у себя аналогичный сервис, и так же просить перевозчиков слать данные и туда тоже? Или есть какой то способ тянуть уже собранные вами данные?

**Comment by norn** [comment]
> То есть подключиться, как описано здесь https://ru.busti.me/services/, можно только в том плане, что перевозчик будет отправлять свои данные в bustime? А получить эти собранные данные никак нельзя, можно только поднять у себя аналогичный сервис, и так же просить перевозчиков слать данные и туда тоже? Или есть какой то способ тянуть уже собранные вами данные?

​Если вы являетесь владельцем данных или обладаете правом на их ретрансляцию, то вы можете получить доступ к отправляемым вами данным. Можем предоставлять их обратно в формате [Bustime](https://github.com/norn/bustime/blob/master/docs/protocol/ru.md), а также добавить необходимые поля, рассчитываемые системой. Пожалуйста, свяжитесь с нами по адресу [support@busti.me](mailto:support@busti.me) для получения подробной информации.
